version: 2

models:
  - name: sources
    desription: All dbt nodes that are sources.
    columns:
      - name: id
        data_tests:
          - primary_key
      - name: source_id
        data_tests:
          - not_null
          - expression_is_true:
              arguments:
                expression: "LIKE 'source.spice_rack.%'"