name: 'spice_rack'
version: '2.0.0'
config-version: 2

profile: 'spice_rack'

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  
clean-targets:         
    - "target"
    - "dbt_modules"

vars:
  delete_bookmarks_table: brine.delete_bookmarks
  dbt_artifacts:
    dbt_artifacts_prefix: target/
    dbt_artifacts_filenames: [run_results, manifest]
  pinned_python_package_versions: ['numpy==1.26.4', 'pandas==2.2.2', 'lightgbm==4.5.0', 'optuna==3.2.0', 'scikit-learn==1.5.2']
  pinned_python_version: '3.11'

on-run-start:
    - "{% if flags.WHICH == 'run' %}{{ view_read_prehook() }}{% endif %}"

on-run-end: 
    - "{% if target.name == 'prod' and flags.WHICH == 'run' %}{{ run_permission_grants() }}{% endif %}"
    - "{% if flags.WHICH == 'run' %}{{ grant_dbt_access(schemas) }}{% endif %}"

models:
  +materialized: table
  +transient: false
  +incremental_strategy: "delete+insert"
  spice_rack:
      allspice:
        +schema: allspice
        +snowflake_warehouse: data_science_warehouse
      anise:
        +schema: anise
        +snowflake_warehouse: data_science_warehouse
      basil:
        +schema: basil
        +snowflake_warehouse: data_science_warehouse
      burdock:
        +schema: burdock
        +snowflake_warehouse: data_science_warehouse
      chili:
        +schema: chili
        +tags: 
          - "chili"
      customerio:
        +schema: customerio
        +tags:
          - "thyme"
          - "parsley"
      dry:
        +schema: dry
        +tags: 
          - "thyme"
      floret:
        +schema: floret
        +tags:
          - "thyme"
          - "parsley"
      grind:
        +schema: grind
        +tags: 
          - "thyme" 
          - "parsley"
          - "looker"
      harvest:
        +schema: harvest
        +tags:
          - "harvest"
      pantry:
        +schema: pantry
        +tags:
          - "thyme"
          - "parsley"
      sage:
        +schema: sage
        +tags: 
          - "thyme" 
          - "parsley"
      season:
        +schema: season
        +tags: 
          - "thyme" 
          - "parsley"
          - "looker"
      wash:
        +schema: wash
        +tags: 
          - "thyme" 
          - "parsley"

seeds:
  spice_rack:
    +schema: salt