version: 2

sources:
  - name: airtable_feedback_collector 
    # For table names that contain escape characters, we need to set quoting to true and use all caps to reference
    quoting:
      identifier: true
    
    tables:
      - name: add_on_reviews
        identifier: FEEDBACK_COLLECTOR/MARKETPLACE_FEEDBACK/TBLCLGSWZZ4XZQPYD
      - name: analytics_keys
        identifier: FEEDBACK_COLLECTOR/ANALYTICS_KEYS/TBL7P2GQUGOUI37DI
      - name: growth_keys
        identifier: FEEDBACK_COLLECTOR/GROWTH_ANALYTICS_KEYS/TBLPLVCPGZVERIWRS
      - name: menu_feedback
        identifier: FEEDBACK_COLLECTOR/MENU_FEEDBACK/TBLJTI9SP9DIONE6I

  - name: airtable_oven_inventory 
    # For table names that contain escape characters, we need to set quoting to true and use all caps to reference
    quoting:
      identifier: true
    
    tables:
      - name: oven_inventory
        identifier: OVEN_INVENTORY/OVEN_INVENTORY/TBLAXQ9DDCHSMVDKA
      - name: rma_request
        identifier: OVEN_INVENTORY/RMA_REQUEST/TBL5CT8JGYPSV8VS6

  - name: brine 
    tables:
      - name: affirm_charges_external
      - name: blessed_at
      - name: blessed_airvalas
      - name: commitment_enforcement_customers
      - name: customers_to_exclude_from_retention_analysis
      - name: dim_calendar 
      - name: dim_calendar_timestamps
      - name: dim_numbers
      - name: direct_mail_curve
      - name: dma_name_mapping
      - name: historical_menu_ratings
      - name: holidays
      - name: new_media_spend_by_channel
      - name: non_tovala_meal_ids
      - name: state_timezones
      - name: subscriptionactivity_timestamp_fixes
      - name: timezonebyzipcode
      - name: weekly_meal_counts
      - name: zipcode_details

  - name: chili
    # Load cadence: 24 hours
    freshness: 
      warn_after: {count: 36, period: hour}
      error_after: {count: 48, period: hour}
    
    loaded_at_field: updated
    tables:
      - name: box_fillometer_logs
        freshness: 
          warn_after: {count: 8, period: day}
          error_after: {count: 9, period: day}
      - name: autofill_results
        # Freshness not applicable
        freshness:
      - name: cdn_menu
        # Freshness not applicable (for now)
        freshness:
          warn_after: {count: 8, period: day}
          error_after: {count: 9, period: day}
      - name: device_to_serial
        # Freshness not applicable
        freshness:
      - name: direct_mail_ccc
        # Freshness not applicable
        freshness:
      - name: experian_customers
      - name: experimental_assignments
        freshness:
      - name: midline
        # Freshness not applicable
        freshness:
      - name: oven_projections
        freshness:
      - name: shipment_file
        # Load cadence: weekly
        freshness: 
          warn_after: {count: 8, period: day}
          error_after: {count: 9, period: day}
      - name: table_snapshots
      - name: tovala_assist
        # Freshness not applicable
        freshness:
      - name: tovala_preset
        # Freshness not applicable
        freshness:
      - name: customer_advisory_board
        # Freshness not applicable (for now)
        freshness:

  - name: combined_api_v3
    # Load cadence: 1 hour

    loaded_at_field: _airbyte_extracted_at
    tables:
      - name: affirm_charges
      - name: barcodes
      - name: cookable_assist_recipe_reviews
      - name: cookable_meal_reviews
      - name: cookable_reviews
      - name: cookable_review_chips
      - name: cookable_review_chip_selections
      - name: coupon_codes
      - name: coupon_codes_applied
      - name: delete_logs
      - name: discount_offer_channel 
      - name: gift_cards
      - name: gift_cards_activity
      - name: location
      - name: mealcountsallowed
      - name: mealimages
      - name: mealreviews
      - name: meals
      - name: mealselections
      - name: meal_soldout_counts
      - name: meal_soldout_event
      - name: mealtagmap
      - name: mealtags
      - name: meal_cashmoney
      - name: memberships
      - name: membership_orders
        freshness:
      - name: membership_types
      - name: menu_anticombos
      - name: menu_meals
      - name: menu_product_listing_attachments
      - name: menu_product_listing_sections
        freshness:
      - name: menu_product_listing_sections_layout
        freshness:
      - name: menu_product_listings
      - name: menu_product_order_listing_selections
        freshness:
          warn_after: {count: 8, period: day}
          error_after: {count: 9, period: day}
      - name: menu_product_orders
      - name: menu_products
      - name: menus
      - name: ops_guidance_events 
      - name: orderboxes
      - name: orderfulfillment
      - name: order_discount 
      - name: order_discount_offering
      - name: order_refund_event
      - name: orders_pos_mappings
      - name: oven_hardware_information_history
        freshness:
      - name: oven_hardware_information
        freshness:
      - name: oven_roadshows
        freshness:
      - name: ovenorderfulfillment
      - name: ovens
      - name: ovens_history
      - name: ovens_tovala
      - name: payment
      - name: payment_line_item
      - name: products
      - name: products_purchase
      - name: products_shipment
      - name: reactivation_credits
      - name: stripefingerprints
      - name: stripesubscriptions
      - name: sts_products
      - name: subscriptionactivity
      - name: subterms
      - name: subterm_zipcodes
      - name: subterm_zipcodes_shipping_information
      - name: terms
      - name: termskips
      - name: termskips_log
      - name: third_party_purchases
      - name: tovala_assist_recipe_reviews
      - name: usermealdatajson
      - name: users
      - name: users_affected_by_ops_guidance_events
      - name: usertags
      - name: user_menu_product_listing_selections
      - name: user_subscription_break_history
      - name: user_subscription_breaks
      - name: user_term_order
      - name: user_term_order_offers
      - name: user_term_status
      - name: user_term_status_audit
      - name: zipcodes
      - name: zipcode_shipping_information

  - name: dbt_artifacts
    database: "{{ var('dbt_artifacts_database', target.database) }}"
    schema: "{{ var('dbt_artifacts_schema', 'dbt_artifacts') }}"
    tables:
      - name: artifacts
        identifier: "{{ var('dbt_artifacts_table', 'artifacts') }}"

  - name: experiment_tracker_v2

    loaded_at_field: _airbyte_extracted_at
    tables:
      - name: experiments
      - name: variants
      - name: experiments_seen
  
  - name: facebook_ads
    # Load cadence: 24 hours
    freshness: 
      warn_after: {count: 36, period: hour}
      error_after: {count: 48, period: hour}

    loaded_at_field: _airbyte_extracted_at
    tables:
      - name: ads_insights
      - name: ads_insights_platform_and_device
      - name: ads_insights_age_and_gender

  - name: fullstory_data_export
    # Load cadence: 1 hour
    freshness: 
      warn_after: {count: 12, period: hour}
      error_after: {count: 24, period: hour}

    loaded_at_field: _sdc_received_at
    tables:
      - name: events
  
  - name: google_ads
    # Load cadence: 24 hours
    freshness: 
      warn_after: {count: 36, period: hour}
      error_after: {count: 48, period: hour}

    loaded_at_field: _airbyte_extracted_at
    tables:
      - name: campaign
      - name: campaign_label
      - name: keyword_view 

  - name: growth_team_daily_sales_projections
    # Load cadence: 24 hours
    freshness:
      warn_after: {count: 36, period: hour}
      error_after: {count: 48, period: hour}

    loaded_at_field: _airbyte_extracted_at
    tables:
      - name: daily_oven_sales_projections
  
  - name: impact
    # Load cadence: 24 hours
    freshness: 
      warn_after: {count: 36, period: hour}
      error_after: {count: 48, period: hour}

    loaded_at_field: _airbyte_extracted_at
    tables:
      - name: performance_by_day

  - name: information_schema
    tables:
      - name: columns
      - name: load_history

  - name: kinesis
    # Load cadence: 4 hours
    freshness: 
      warn_after: {count: 6, period: hour}
      error_after: {count: 12, period: hour}
    
    loaded_at_field: updated
    tables:
      - name: micro_logs_combined
      - name: oven_logs
      - name: oven_logs_combined
  
  - name: meal_tags
    # Load cadence: 24 hours
    freshness:
      warn_after: {count: 36, period: hour}
      error_after: {count: 48, period: hour}

    loaded_at_field: _airbyte_extracted_at
    tables:
      - name: meal_sku_costs
      - name: meal_sku_tags

  - name: microsoft_ads
    # Load cadence: 24 hours
    freshness: 
      warn_after: {count: 36, period: hour}
      error_after: {count: 48, period: hour}

    loaded_at_field: _airbyte_extracted_at
    tables:
      - name: account_performance_report_daily

  - name: modus
    # Load cadence: 24 hours
    freshness: 
      warn_after: {count: 36, period: hour}
      error_after: {count: 48, period: hour}

    loaded_at_field: _airbyte_extracted_at
    tables:
      - name: tv_spot
      - name: customer 
      - name: crm_customer 
  
  - name: mold 
    tables:
      - name: costco_retail_sales
      - name: costco_roadshows
      - name: costco_serials
      - name: qvc_retail_sales

  - name: misevala_v3
    tables:
      - name: delete_logs
      - name: facility_network
      - name: part_pgs
      - name: production_meal_info
      - name: production_parts
      - name: production_part_boms
      - name: purchased_goods

  - name: orders_pos
    tables: 
      - name: invoices 
      - name: invoice_charges 
      - name: invoice_payments 
      - name: invoice_refunds
      - name: invoice_status 
      - name: orders 

  - name: retool
    tables:
      - name: term_labor_costs

  - name: sigma_input_tables
    tables:
      - name: channel_dimensions
      - name: channel_spend_details
      - name: commitment_enforcement_entry
      - name: direct_mail_key_codes_output
      - name: direct_mail_key_codes_output_post_mar_2025
      - name: facebook_ad_tags_output_table
      - name: in_home_date_output_table
      - name: menu_add_ons_input
      - name: oven_cogs_per_month
      - name: sales_period_output
      - name: snowflake_ip_whitelist_input
      - name: spotlight_tv_orders 

  - name: stripe
    # Load cadence: 12 hours
    freshness: 
      warn_after: {count: 36, period: hour}
      error_after: {count: 48, period: hour}

    loaded_at_field: _airbyte_extracted_at
    tables:
      - name: balance_transactions
      - name: charges
      - name: disputes

  - name: supermetrics
    # Load cadence: 24 hours
    freshness: 
      warn_after: {count: 48, period: hour}
      error_after: {count: 60, period: hour}

    loaded_at_field: date::TIMESTAMP
    tables:
      - name: fbads_facebook_ads
      - name: fbads_facebook_ads_by_placement
      - name: fbads_facebook_ads_by_user
      - name: fbads_facebook_ads_by_dma
      - name: fbads_facebook_ads_by_state
      - name: ggl_sc_google_search_console
      - name: googleads_google_ads
      - name: tik_tiktok_ads
        # Off as of 11/29/22
        freshness:
    
  - name: typeform
    # Load cadence: 24 hours
    freshness:
      warn_after: {count: 36, period: hour}
      error_after: {count: 48, period: hour}

    loaded_at_field: _airbyte_extracted_at
    tables:
      - name: forms
      - name: responses

  - name: tvsquared
    # Load cadence: weekly

    freshness:
      warn_after: {count: 8, period: day}
      error_after: {count: 9, period: day}
    
    tables:
      - name: action
      - name: response
      # We are not actively importing spots due to an unresolved file encoding issue with TVSquared
      # This table has some spots data from a manual import test
      # keeping it to avoid breaking downstream tables once chili.tvsquared is gone
      # Freshness not applicable
      - name: spots
        freshness: 

  - name: zendesk_support_v3
    # Load cadence: 1 hour
    freshness: 
      warn_after: {count: 12, period: hour}
      error_after: {count: 24, period: hour}

    loaded_at_field: _airbyte_extracted_at
    tables:
      - name: groups
        freshness: 
      - name: tickets  
      - name: ticket_comments
      - name: ticket_fields
      - name: ticket_metrics
      - name: users
  