version: 2

models:
  - name: production_meal_tags
    description: “This table contain meal tags are internally useful for Autofill."
    columns:
      - name: menu_meal_id 
        description: "Primary Key"
        data_tests:
          - primary_key
          